/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TechRouteImport } from './routes/tech'
import { Route as ScrapsRouteImport } from './routes/scraps'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as ScrapsIndexRouteImport } from './routes/scraps.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkIdRouteImport } from './routes/work.$id'
import { Route as ScrapsSlugRouteImport } from './routes/scraps.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as AdminWorksRouteImport } from './routes/admin.works'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScrapsRouteImport } from './routes/admin.scraps'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminWorksIndexRouteImport } from './routes/admin.works.index'
import { Route as AdminScrapsIndexRouteImport } from './routes/admin.scraps.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as ApiBlogAssetsProxyRouteImport } from './routes/api.blog-assets.proxy'
import { Route as AdminWorksNewRouteImport } from './routes/admin.works.new'
import { Route as AdminWorksIdRouteImport } from './routes/admin.works.$id'
import { Route as AdminScrapsNewRouteImport } from './routes/admin.scraps.new'
import { Route as AdminScrapsSlugRouteImport } from './routes/admin.scraps.$slug'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogSlugRouteImport } from './routes/admin.blog.$slug'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesSlugRouteImport } from './routes/admin.articles.$slug'
import { Route as ApiBlogAssetsTempSplatRouteImport } from './routes/api.blog-assets.temp.$'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapsRoute = ScrapsRouteImport.update({
  id: '/scraps',
  path: '/scraps',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechRoute,
} as any)
const ScrapsIndexRoute = ScrapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScrapsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkIdRoute = WorkIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkRoute,
} as any)
const ScrapsSlugRoute = ScrapsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScrapsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorksRoute = AdminWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScrapsRoute = AdminScrapsRouteImport.update({
  id: '/scraps',
  path: '/scraps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksIndexRoute = AdminWorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWorksRoute,
} as any)
const AdminScrapsIndexRoute = AdminScrapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminScrapsRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const ApiBlogAssetsProxyRoute = ApiBlogAssetsProxyRouteImport.update({
  id: '/api/blog-assets/proxy',
  path: '/api/blog-assets/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorksNewRoute = AdminWorksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminWorksRoute,
} as any)
const AdminWorksIdRoute = AdminWorksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWorksRoute,
} as any)
const AdminScrapsNewRoute = AdminScrapsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminScrapsRoute,
} as any)
const AdminScrapsSlugRoute = AdminScrapsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminScrapsRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogSlugRoute = AdminBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminArticlesSlugRoute = AdminArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const ApiBlogAssetsTempSplatRoute = ApiBlogAssetsTempSplatRouteImport.update({
  id: '/api/blog-assets/temp/$',
  path: '/api/blog-assets/temp/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/author': typeof AuthorRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/scraps': typeof ScrapsRouteWithChildren
  '/tech': typeof TechRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/scraps': typeof AdminScrapsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/works': typeof AdminWorksRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/work/$id': typeof WorkIdRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/scraps/': typeof ScrapsIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/scraps/$slug': typeof AdminScrapsSlugRoute
  '/admin/scraps/new': typeof AdminScrapsNewRoute
  '/admin/works/$id': typeof AdminWorksIdRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/api/blog-assets/proxy': typeof ApiBlogAssetsProxyRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/scraps/': typeof AdminScrapsIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/api/blog-assets/temp/$': typeof ApiBlogAssetsTempSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/work/$id': typeof WorkIdRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/scraps': typeof ScrapsIndexRoute
  '/tech': typeof TechIndexRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/scraps/$slug': typeof AdminScrapsSlugRoute
  '/admin/scraps/new': typeof AdminScrapsNewRoute
  '/admin/works/$id': typeof AdminWorksIdRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/api/blog-assets/proxy': typeof ApiBlogAssetsProxyRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/scraps': typeof AdminScrapsIndexRoute
  '/admin/works': typeof AdminWorksIndexRoute
  '/api/blog-assets/temp/$': typeof ApiBlogAssetsTempSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/author': typeof AuthorRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/scraps': typeof ScrapsRouteWithChildren
  '/tech': typeof TechRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/scraps': typeof AdminScrapsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/works': typeof AdminWorksRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/work/$id': typeof WorkIdRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/scraps/': typeof ScrapsIndexRoute
  '/tech/': typeof TechIndexRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/scraps/$slug': typeof AdminScrapsSlugRoute
  '/admin/scraps/new': typeof AdminScrapsNewRoute
  '/admin/works/$id': typeof AdminWorksIdRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/api/blog-assets/proxy': typeof ApiBlogAssetsProxyRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/scraps/': typeof AdminScrapsIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/api/blog-assets/temp/$': typeof ApiBlogAssetsTempSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/author'
    | '/blog'
    | '/contact'
    | '/scraps'
    | '/tech'
    | '/work'
    | '/admin/articles'
    | '/admin/blog'
    | '/admin/comments'
    | '/admin/scraps'
    | '/admin/settings'
    | '/admin/works'
    | '/api/contact'
    | '/articles/$slug'
    | '/blog/$slug'
    | '/scraps/$slug'
    | '/work/$id'
    | '/admin/'
    | '/articles/'
    | '/blog/'
    | '/scraps/'
    | '/tech/'
    | '/admin/articles/$slug'
    | '/admin/articles/new'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/admin/scraps/$slug'
    | '/admin/scraps/new'
    | '/admin/works/$id'
    | '/admin/works/new'
    | '/api/blog-assets/proxy'
    | '/admin/articles/'
    | '/admin/blog/'
    | '/admin/scraps/'
    | '/admin/works/'
    | '/api/blog-assets/temp/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/author'
    | '/contact'
    | '/work'
    | '/admin/comments'
    | '/admin/settings'
    | '/api/contact'
    | '/articles/$slug'
    | '/blog/$slug'
    | '/scraps/$slug'
    | '/work/$id'
    | '/admin'
    | '/articles'
    | '/blog'
    | '/scraps'
    | '/tech'
    | '/admin/articles/$slug'
    | '/admin/articles/new'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/admin/scraps/$slug'
    | '/admin/scraps/new'
    | '/admin/works/$id'
    | '/admin/works/new'
    | '/api/blog-assets/proxy'
    | '/admin/articles'
    | '/admin/blog'
    | '/admin/scraps'
    | '/admin/works'
    | '/api/blog-assets/temp/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/author'
    | '/blog'
    | '/contact'
    | '/scraps'
    | '/tech'
    | '/work'
    | '/admin/articles'
    | '/admin/blog'
    | '/admin/comments'
    | '/admin/scraps'
    | '/admin/settings'
    | '/admin/works'
    | '/api/contact'
    | '/articles/$slug'
    | '/blog/$slug'
    | '/scraps/$slug'
    | '/work/$id'
    | '/admin/'
    | '/articles/'
    | '/blog/'
    | '/scraps/'
    | '/tech/'
    | '/admin/articles/$slug'
    | '/admin/articles/new'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/admin/scraps/$slug'
    | '/admin/scraps/new'
    | '/admin/works/$id'
    | '/admin/works/new'
    | '/api/blog-assets/proxy'
    | '/admin/articles/'
    | '/admin/blog/'
    | '/admin/scraps/'
    | '/admin/works/'
    | '/api/blog-assets/temp/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthorRoute: typeof AuthorRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ScrapsRoute: typeof ScrapsRouteWithChildren
  TechRoute: typeof TechRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiBlogAssetsProxyRoute: typeof ApiBlogAssetsProxyRoute
  ApiBlogAssetsTempSplatRoute: typeof ApiBlogAssetsTempSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraps': {
      id: '/scraps'
      path: '/scraps'
      fullPath: '/scraps'
      preLoaderRoute: typeof ScrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/scraps/': {
      id: '/scraps/'
      path: '/'
      fullPath: '/scraps/'
      preLoaderRoute: typeof ScrapsIndexRouteImport
      parentRoute: typeof ScrapsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof WorkRoute
    }
    '/scraps/$slug': {
      id: '/scraps/$slug'
      path: '/$slug'
      fullPath: '/scraps/$slug'
      preLoaderRoute: typeof ScrapsSlugRouteImport
      parentRoute: typeof ScrapsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/works': {
      id: '/admin/works'
      path: '/works'
      fullPath: '/admin/works'
      preLoaderRoute: typeof AdminWorksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scraps': {
      id: '/admin/scraps'
      path: '/scraps'
      fullPath: '/admin/scraps'
      preLoaderRoute: typeof AdminScrapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/': {
      id: '/admin/works/'
      path: '/'
      fullPath: '/admin/works/'
      preLoaderRoute: typeof AdminWorksIndexRouteImport
      parentRoute: typeof AdminWorksRoute
    }
    '/admin/scraps/': {
      id: '/admin/scraps/'
      path: '/'
      fullPath: '/admin/scraps/'
      preLoaderRoute: typeof AdminScrapsIndexRouteImport
      parentRoute: typeof AdminScrapsRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/api/blog-assets/proxy': {
      id: '/api/blog-assets/proxy'
      path: '/api/blog-assets/proxy'
      fullPath: '/api/blog-assets/proxy'
      preLoaderRoute: typeof ApiBlogAssetsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/works/new': {
      id: '/admin/works/new'
      path: '/new'
      fullPath: '/admin/works/new'
      preLoaderRoute: typeof AdminWorksNewRouteImport
      parentRoute: typeof AdminWorksRoute
    }
    '/admin/works/$id': {
      id: '/admin/works/$id'
      path: '/$id'
      fullPath: '/admin/works/$id'
      preLoaderRoute: typeof AdminWorksIdRouteImport
      parentRoute: typeof AdminWorksRoute
    }
    '/admin/scraps/new': {
      id: '/admin/scraps/new'
      path: '/new'
      fullPath: '/admin/scraps/new'
      preLoaderRoute: typeof AdminScrapsNewRouteImport
      parentRoute: typeof AdminScrapsRoute
    }
    '/admin/scraps/$slug': {
      id: '/admin/scraps/$slug'
      path: '/$slug'
      fullPath: '/admin/scraps/$slug'
      preLoaderRoute: typeof AdminScrapsSlugRouteImport
      parentRoute: typeof AdminScrapsRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$slug': {
      id: '/admin/blog/$slug'
      path: '/$slug'
      fullPath: '/admin/blog/$slug'
      preLoaderRoute: typeof AdminBlogSlugRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/articles/$slug': {
      id: '/admin/articles/$slug'
      path: '/$slug'
      fullPath: '/admin/articles/$slug'
      preLoaderRoute: typeof AdminArticlesSlugRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/api/blog-assets/temp/$': {
      id: '/api/blog-assets/temp/$'
      path: '/api/blog-assets/temp/$'
      fullPath: '/api/blog-assets/temp/$'
      preLoaderRoute: typeof ApiBlogAssetsTempSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesSlugRoute: typeof AdminArticlesSlugRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesSlugRoute: AdminArticlesSlugRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminBlogRouteChildren {
  AdminBlogSlugRoute: typeof AdminBlogSlugRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogSlugRoute: AdminBlogSlugRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminScrapsRouteChildren {
  AdminScrapsSlugRoute: typeof AdminScrapsSlugRoute
  AdminScrapsNewRoute: typeof AdminScrapsNewRoute
  AdminScrapsIndexRoute: typeof AdminScrapsIndexRoute
}

const AdminScrapsRouteChildren: AdminScrapsRouteChildren = {
  AdminScrapsSlugRoute: AdminScrapsSlugRoute,
  AdminScrapsNewRoute: AdminScrapsNewRoute,
  AdminScrapsIndexRoute: AdminScrapsIndexRoute,
}

const AdminScrapsRouteWithChildren = AdminScrapsRoute._addFileChildren(
  AdminScrapsRouteChildren,
)

interface AdminWorksRouteChildren {
  AdminWorksIdRoute: typeof AdminWorksIdRoute
  AdminWorksNewRoute: typeof AdminWorksNewRoute
  AdminWorksIndexRoute: typeof AdminWorksIndexRoute
}

const AdminWorksRouteChildren: AdminWorksRouteChildren = {
  AdminWorksIdRoute: AdminWorksIdRoute,
  AdminWorksNewRoute: AdminWorksNewRoute,
  AdminWorksIndexRoute: AdminWorksIndexRoute,
}

const AdminWorksRouteWithChildren = AdminWorksRoute._addFileChildren(
  AdminWorksRouteChildren,
)

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminScrapsRoute: typeof AdminScrapsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWorksRoute: typeof AdminWorksRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminScrapsRoute: AdminScrapsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWorksRoute: AdminWorksRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ScrapsRouteChildren {
  ScrapsSlugRoute: typeof ScrapsSlugRoute
  ScrapsIndexRoute: typeof ScrapsIndexRoute
}

const ScrapsRouteChildren: ScrapsRouteChildren = {
  ScrapsSlugRoute: ScrapsSlugRoute,
  ScrapsIndexRoute: ScrapsIndexRoute,
}

const ScrapsRouteWithChildren =
  ScrapsRoute._addFileChildren(ScrapsRouteChildren)

interface TechRouteChildren {
  TechIndexRoute: typeof TechIndexRoute
}

const TechRouteChildren: TechRouteChildren = {
  TechIndexRoute: TechIndexRoute,
}

const TechRouteWithChildren = TechRoute._addFileChildren(TechRouteChildren)

interface WorkRouteChildren {
  WorkIdRoute: typeof WorkIdRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkIdRoute: WorkIdRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthorRoute: AuthorRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ScrapsRoute: ScrapsRouteWithChildren,
  TechRoute: TechRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiBlogAssetsProxyRoute: ApiBlogAssetsProxyRoute,
  ApiBlogAssetsTempSplatRoute: ApiBlogAssetsTempSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
